# Generated by Django 5.0.1 on 2024-01-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_link', models.CharField(max_length=20)),
                ('long_link', models.URLField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
